behaviors:
  HealthcareDDA:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0005
      learning_rate_schedule: linear
      batch_size: 64
      buffer_size: 512
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 4.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 4.0
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000
    time_horizon: 30
    summary_freq: 1000
