behaviors:
  HealthcareDDA:
    trainer_type: a2c
    hyperparameters:
      batch_size: 64
      buffer_size: 512
      learning_rate: 0.0007
      beta: 0.01
      lambd: 0.95
      num_epoch: 1 
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000
    time_horizon: 30
    summary_freq: 1000
