behaviors:
  HealthcareDDA:
    trainer_type: dqn
    hyperparameters:
      learning_rate: 0.00075
      learning_rate_schedule: constant
      batch_size: 64
      buffer_size: 512
      tau: 0.005
      steps_per_update: 4.0
      save_replay_buffer: false
      exploration_schedule: linear
      exploration_initial_eps: 0.8
      exploration_final_eps: 0.05
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000
    time_horizon: 30
    summary_freq: 1000
